### ISSUE TITLE
Immediate drawing is faster than retained drawing ??

### ISSUE THREAD

**Issue by Pieresqi** [james-j-obrien/bevy_vector_shapes#14]
Hi, I have been playing around with your crate and I have noticed some, what I think is, peculiarity.

That is immediate drawing is 10..20% faster than retained. 
I think it should have been same or retained faster...after all retained should do less than immediate, right ?

```rust
use bevy::{prelude::*, diagnostic::{FrameTimeDiagnosticsPlugin, LogDiagnosticsPlugin}};
use bevy_vector_shapes::prelude::*;

fn main() {
    App::new()
    .add_plugins(DefaultPlugins)
    .add_plugin(FrameTimeDiagnosticsPlugin::default())
    .add_plugin(LogDiagnosticsPlugin::default())
    .add_plugin(Shape2dPlugin::default())
    .insert_resource(ClearColor(Color::NONE))
    .insert_resource(Msaa::Off)
    .add_system(setup.on_startup())
    //.add_system(_draw_retained.on_startup())
    //.add_system(_draw_immediate)
    .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

fn _draw_retained(mut painter: ShapeCommands) {
    for p1 in -250..=250 {
        for p2 in -20..=20 {
            painter.color = Color::WHITE;
            painter.set_translation(Vec3 { x: p1 as f32, y: p2 as f32, z: 0.0 });
            painter.rect(Vec2 { x: 1.0, y: 1.0 });
        }
    }
}

fn _draw_immediate(mut painter: ShapePainter) {
    for p1 in -250..=250 {
        for p2 in -20..=20 {
            painter.color = Color::WHITE;
            painter.set_translation(Vec3 { x: p1 as f32, y: p2 as f32, z: 0.0 });
            painter.rect(Vec2 { x: 1.0, y: 1.0 });
        }
    }    
}

```
Running debug on my pc will yield this:
immediate: 49fps, 
retained: 40fps,

Are my assumptions wrong? Or I am "testing" it wrong ? Or it's really slower ?

Thank you for your time.

**Comment by james-j-obrien** [comment]
I hadn't tested the relative speeds but I'm not surprised by this. Both immediate and retained mode rendering use the same rendering pipeline. The primary difference between the two performance wise is that with immediate mode no entities are created and instead the data is passed along directly to the rendering pipeline, whereas in retained mode we have to query for the entities and then extract them for rendering. Having to extract the data from the ECS rather than have it already prepared is likely responsible for the difference here.

Supporting retained mode is not aimed at performance so much as allowing the user to modify the shapes rather than having to redraw all of them every frame. On the other hand immediate mode is designed to have as little overhead as possible.

I might be able to improve retained performance by caching the extracted data so we don't need to re-extract each frame, however in cases where the shapes are changing often this won't have a huge impact. I'll investigate adding this functionality as part of the upgrade to bevy 0.11.

**Comment by Pieresqi** [comment]
Ok, Thank you.
