### ISSUE TITLE
HDR Alpha bleeding

### ISSUE THREAD

**Issue by IDEDARY** [james-j-obrien/bevy_vector_shapes#20]
When using SpriteBundle with Z that is under ShapePainter .set_transform(Z), the alpha of the images will bleed though the ShapePainter.

Troubleshooting camera settings:
* Tonemapping: No effect
* Bloom: No effect
* HDR on/off: Solves issue

I also attached the project the bug occurred in, so anybody can hop directly to fixing it instead of spending time replicating the error.
source code to the relevant [repository](https://ufile.io/c5kexoxw)

![image](https://github.com/james-j-obrien/bevy_vector_shapes/assets/49441831/a5bcf174-07ec-4b5b-912e-cf9ae238d0a1)

**Comment by james-j-obrien** [comment]
This is quite an interesting effect but I think you can fix this by adding:
``` painter.color.set_a(1.0); ```
before you draw, because of the lazy way I transform the color in the pastel function in my examples it sets the alpha to 2.0 in your example, this has no affect on non-HDR cameras because they don't care about any alpha above 1.0 but for HDR apparently it does this.

Let me know if this fixes it for you and if you encounter any other weird behaviour.

**Comment by james-j-obrien** [comment]
I've fixed the implementation of `pastel` in the examples so I don't accidentally pass this on to someone else.

**Comment by IDEDARY** [comment]
I see. Yes, that fixed the issue. Thank you.
Just for curiosity, I recreated the rectangle with just a white image set to a same color. Had the same **weird** bug.
So it's a general Bevy thing.
