### ISSUE TITLE
Spawning a canvas at any point away from the origin

### ISSUE THREAD

**Issue by spooky-th-ghost** [james-j-obrien/bevy_vector_shapes#24]
I'm currently doing some experiments in a fork at the moment and I've noticed that even when the transform component of the canvas entity is updated, anything drawn by a `ShapePainter` will move accordingly but it cannot be drawn outside the original canvas size, this all makes sense but I'm wondering if there is a way to offset the canvas based on it's translation

**Comment by james-j-obrien** [comment]
A canvas is effectively just a camera (it's spawned with the Camera2dBundle). If you modify it's transform it will effectively offset the shapes you draw to it in the same way that moving any other camera would affect what it renders.

**Comment by spooky-th-ghost** [comment]
That's what I had figured, with a canvas size of 256x256, if i move the canvas entity to `(0.0,128.0,0.0)` only the top half of the canvas is able to be drawn
Origin:
![image](https://github.com/james-j-obrien/bevy_vector_shapes/assets/30451500/aa4aaed1-4f64-4fd1-9cd2-12ddd58019f9)

Moved
![image](https://github.com/james-j-obrien/bevy_vector_shapes/assets/30451500/e0106857-cb84-4ba6-9330-a142332aba44)

**Comment by james-j-obrien** [comment]
Is that unexpected? If you move the camera then the shapes that fall out of the view of the camera will be cut off.

If you want the shapes to move with the canvas (which would cancel out their movement so I'm not sure of the goal) you can either parent them to the canvas or just set the painter to the position of the canvas when you draw.

Testing locally I'm not seeing any odd behavior but perhaps you are doing something I'm not.

**Comment by spooky-th-ghost** [comment]
I think parenting them to the canvas is what I'm after, I think the thing tripping me up is the shapes themselves not being an entity

**Comment by james-j-obrien** [comment]
You also have the option of using `ShapeCommands` instead of `ShapePainter` to spawn actual entities that persist between frames and that you can modify in systems, it just means not creating new ones every frame.

If you want the render of the canvas to move you can move the shape you are drawing the canvas onto.
i.e. set the transform of the `ShapePainter` before a call to `.image()`/drawing a shape with the canvas texture set OR modify the `Transform` of that shape when using `ShapeCommands`

If you want to move all the shapes within the canvas you can move the canvas itself (moving the camera).
i.e. modify the `Transform` of the canvas entity

Moving the canvas and the shapes inside should visually do nothing.
