### ISSUE TITLE
Some helpful comments?

### ISSUE THREAD

**Issue by musjj** [james-j-obrien/bevy_vector_shapes#27]
I'm trying to comprehend how this library works, but I just can't wrap my head around this. For example, why are 3D cameras used when using canvases? When I used a 2D camera, nothing gets rendered.

https://github.com/james-j-obrien/bevy_vector_shapes/blob/94f9e4b7fcc2d48020336782951241fb098289da/examples/canvas_basic.rs#L20-L26

What are those magic numbers (`0., 0., 16.`)?

https://github.com/james-j-obrien/bevy_vector_shapes/blob/94f9e4b7fcc2d48020336782951241fb098289da/examples/canvas_basic.rs#L30-L31

What does this do? Again what are those magic numbers? Why are we setting the size? The function seems entirely undocumented.

https://github.com/james-j-obrien/bevy_vector_shapes/blob/94f9e4b7fcc2d48020336782951241fb098289da/examples/canvas_basic.rs#L34

Why are we scaling it here? Once again I am stumped by an unexplained magic number.

I'm particular struggling to get it to display at the right aspect ratio. Some small comments sprinkled here and there will really help new users like me from going nuts.

**Comment by james-j-obrien** [comment]
The reason you aren't getting anything to render with a 2d camera is that bevy has very different scales for 2d and 3d hence the x48 scale before rendering the gallery. You will notice across the examples that whenever I render the gallery in 2d I have to scale it down first.

The constant vec in the camera transform is to move the camera away from the origin because otherwise we wouldn't be able to see the canvas we draw at 0,0,0.

**Comment by musjj** [comment]
Thanks, I switched to the `Shape2dPlugin` instead and now everything works with the 2D camera. Doing things directly in 2D just makes a lot more sense to me. No more juggling with units, you draw a pixel length, you get a pixel length.

Just curious, but is there a reason for using a 3D camera for 2D vectors? Most of the examples are done in 3D (even though the results are basically 2D), to the point that I didn't realize there's a 2D version. The non-explicit naming of the plugin didn't help either.

**Comment by james-j-obrien** [comment]
The reason ShapePlugin is not called Shape3dPlugin is not only because it's consistent with bevy but because the 3d plugin includes all the 2d functionality to support canvases. If you set a painter to 2d and scale everything correctly you can still draw shapes to a 2d camera with the non 2d plugin.

Supporting 3d is important because people like to use this library for in world UI which requires positioning the shapes in 3d space on 3d cameras.
