### ISSUE TITLE
Combine multiple shapes into a single bundle

### ISSUE THREAD

**Issue by musjj** [james-j-obrien/bevy_vector_shapes#28]
It would be nice if we can combine multiple shapes into a single bundle (https://github.com/james-j-obrien/bevy_vector_shapes/blob/main/examples/bundles.rs).

Since bevy does not allow "duplicate" components, you can't really make a bundle out of multiple shapes. Right now, I'm working around this by manually doing `.insert(shape)`, with works for some reason, but it only works for different shapes.

**Comment by james-j-obrien** [comment]
In order to have multiple of the same shape you must have multiple entities as the shape is made up of components on the entity. The reason inserting different shapes works is the entity then gets interpreted as both kinds of shape since it has the components for both. If you want have multiple of the same shape move together parenting is a good option.

**Comment by james-j-obrien** [comment]
Yes, there is also support for this build into the library that you can check out in the parenting examples
