### ISSUE TITLE
Painter configuration not shared between different systems?

### ISSUE THREAD

**Issue by musjj** [james-j-obrien/bevy_vector_shapes#29]
I'm trying to split my systems between configuration (`painter.translate`, etc.) and the painting (`painter.circle`, etc.), but for some reason I'm unable to share the configuration between systems.

I've used scheduling sets to make sure that the configuration always happens before the painting, but I'm still unable to share the state of the painter between systems.

**Comment by james-j-obrien** [comment]
By design painter configuration is constrained to the system however there is a shared `BaseShapeConfig` resource. When you call `.reset()` on a painter it is reset to the value in that resource so if you would like you can simply modify the resource and reset your painter before use, alternatively you can extract the config and store it yourself with `.config` and `.set_config`.

**Comment by james-j-obrien** [comment]
Putting external types into unit structs so you can mark them as a component is a pretty common pattern in bevy so that's what I'd suggest if all you want to store is the config.

The reason people don't just mark all structs as components is so that two dependencies don't both start using it without being aware of each other and causing conflicts (although I do admit in this case that would probably be unlikely).

**Comment by musjj** [comment]
You're right, it looks like that it's a pretty idiomatic pattern in Bevy so I'll go with that then, thanks!
