### ISSUE TITLE
Batch Splitting

### ISSUE THREAD

**Issue by james-j-obrien** [james-j-obrien/bevy_vector_shapes#5]
Due to all shapes being instanced together there is the potential for z-ordering issues when interleaving different kinds of shapes or interleaving shapes with other meshes. This can be resolved by splitting the batches, while this would be very achievable for shapes it may require changes in bevy in order to generalize across all meshes and will always come with a performance hit.
Eventually when bevy has instancing and batching support natively this issue maybe solved without further library work.

**Comment by StarArawn** [comment]
You should be able to solve this by moving away from instanced rendering for 2D and instead use batch rendering like `bevy_sprite`. For quads instancing is actually less than optimal because you end up wasting wavefronts on the GPU(GPU process vertices in batches of 32 or 64 so draw calls with less vertices tie up performance). Great read here:
https://www.slideshare.net/DevCentralAMD/vertex-shader-tricks-bill-bilodeau

**Comment by james-j-obrien** [comment]
Very interesting, thanks for the link, will follow through on this shortly.

**Comment by Elabajaba** [comment]
> You should be able to solve this by moving away from instanced rendering for 2D and instead use batch rendering like `bevy_sprite`. For quads instancing is actually less than optimal because you end up wasting wavefronts on the GPU(GPU process vertices in batches of 32 or 64 so draw calls with less vertices tie up performance). Great read here: https://www.slideshare.net/DevCentralAMD/vertex-shader-tricks-bill-bilodeau

Not necessarily true these days, as some (AMD, probably Nvidia, others idk) GPU drivers can and will merge instances together for better occupancy.

**Comment by james-j-obrien** [comment]
This is resolved in my bevy 0.12 branch: https://github.com/james-j-obrien/bevy_vector_shapes/tree/bevy-0.12.
